---
deployment:
  tasks:
    # This line activates the correct Node.js version
    - export PATH=/home/fedz/nodevenv/staff.mealvilla.ng/24/bin:$PATH

    # Your "npm install" step
    - npm install

    # Your "npm run build" step
    - npm run build

    # This restarts your "npm start" process
    - mkdir -p tmp
    - touch tmp/restart.txt
