---
deployment:
  tasks:
    # CORRECTED PATH with your username 'lifedzrz'
    - export PATH=/home/lifedzrz/nodevenv/staff.mealvilla.ng/24/bin:$PATH

    # Install project dependencies
    - npm install

    # Build the Next.js application for production
    - npm run build

    # Restart the server to apply the new changes
    - mkdir -p tmp
    - touch tmp/restart.txt
